projects:
  fix-it-now-o8ebuf63:
    url: wss://fix-it-now-o8ebuf63.livekit.cloud
    api_key: APIbaVFuGzwqPGG
    api_secret: qxXJ0OfuxnuKt3E3nmMsTuZf8fjKeX7ipleZ5yT617jH
current_project: fix-it-now-o8ebuf63